[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "readme-rosetta"
version = "0.1.1"
description = "A tool to facilitate the translation of GitHub README.md files using NLLB-200."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Julian Henry"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "ollama",
    "tqdm",
    "polib",
    "rich",
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
dev = ["ruff"]

[tool.ruff]
line-length = 88
target-version = "0.1.1"

[tool.ruff.lint]
select = ["E", "F", "I", "W", "N"]
ignore = []

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
readme-rosetta = "readme_rosetta.cli:main"
