import json

import pytest

from readme_rosetta import cli

from .conftest import FakeBackend

SOURCE = "# 🗿 Demo\n\nTranslate your README into many languages.\n\n```sh\npip install demo\n```\n"


@pytest.fixture
def project(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    (tmp_path / "README.md").write_text(SOURCE, encoding="utf-8")
    backends = []

    def fake_create(name, model, **kw):
        backend = FakeBackend()
        backends.append(backend)
        return backend

    monkeypatch.setattr(cli, "create_backend", fake_create)

    # FakeBackend 'translates' for its own target; make it follow the request.
    original = FakeBackend.complete

    def complete(self, system, messages):
        self.target = "ja" if "into Japanese" in system else "es"
        return original(self, system, messages)

    monkeypatch.setattr(FakeBackend, "complete", complete)
    return tmp_path, backends


def test_split_mode_writes_files_and_nav(project):
    tmp_path, backends = project
    assert cli.main(["--langs", "es", "ja"]) == 0

    readme = (tmp_path / "README.md").read_text(encoding="utf-8")
    es = (tmp_path / "README.es.md").read_text(encoding="utf-8")
    ja = (tmp_path / "README.ja.md").read_text(encoding="utf-8")

    assert readme.startswith(
        "<!-- rosetta:nav:start -->\n🌐 **English** · [Español](README.es.md) · [日本語](README.ja.md)"
    )
    assert readme.endswith(SOURCE)
    assert "Generated by readme-rosetta from README.md" in es
    assert "[English](README.md) · **Español**" in es
    assert "pip install demo" in es and "pip install demo" in ja
    assert "あ" in ja

    cache = json.loads((tmp_path / ".rosetta" / "cache.json").read_text())
    assert cache["version"] == 2 and cache["entries"]


def test_second_run_is_free_and_idempotent(project):
    tmp_path, backends = project
    cli.main(["--langs", "es"])
    first = (tmp_path / "README.md").read_text(encoding="utf-8")
    assert cli.main(["--langs", "es"]) == 0
    assert backends[-1].requests == []
    assert (tmp_path / "README.md").read_text(encoding="utf-8") == first


def test_only_changed_paragraphs_are_retranslated(project):
    tmp_path, backends = project
    cli.main(["--langs", "es"])
    text = (tmp_path / "README.md").read_text(encoding="utf-8")
    (tmp_path / "README.md").write_text(
        text + "\nA brand new paragraph.\n", encoding="utf-8"
    )
    cli.main(["--langs", "es"])
    sent = backends[-1].requests[0][0]["content"]
    assert "brand new paragraph" in sent and "many languages" not in sent


def test_unknown_language_is_an_error(project):
    with pytest.raises(SystemExit, match="hihn"):
        cli.main(["--langs", "hihn"])


def test_failures_exit_non_zero(project, monkeypatch):
    tmp_path, _ = project
    monkeypatch.setattr(FakeBackend, "complete", lambda self, s, m: "no idea")
    assert cli.main(["--langs", "es"]) == 1
    assert cli.main(["--langs", "es", "--allow-fallback"]) == 0


def test_dry_run_writes_nothing(project):
    tmp_path, backends = project
    assert cli.main(["--langs", "es", "--dry-run"]) == 0
    assert not (tmp_path / "README.es.md").exists()
    assert backends == []


def test_config_from_pyproject(project):
    tmp_path, _ = project
    (tmp_path / "pyproject.toml").write_text('[tool.readme-rosetta]\nlangs = ["es"]\n')
    assert cli.main([]) == 0
    assert (tmp_path / "README.es.md").exists()


def test_no_split_mode(project):
    tmp_path, _ = project
    assert cli.main(["--langs", "es", "--no-split"]) == 0
    readme = (tmp_path / "README.md").read_text(encoding="utf-8")
    assert "<!-- rosetta:translation:es -->" in readme
    assert "[Español](#-omedx)" in readme
    assert not (tmp_path / "README.es.md").exists()


def test_gitbook_summary(project):
    tmp_path, _ = project
    assert cli.main(["--langs", "es", "--gitbook"]) == 0
    summary = (tmp_path / "SUMMARY.md").read_text(encoding="utf-8")
    assert "* [Español](README.es.md)" in summary


def test_interrupted_run_keeps_finished_languages_and_cache(project, monkeypatch):
    tmp_path, backends = project
    original = FakeBackend.complete

    def complete(self, system, messages):
        if "into French" in system:
            raise KeyboardInterrupt  # e.g. Ctrl-C or kill while French is running
        return original(self, system, messages)

    monkeypatch.setattr(FakeBackend, "complete", complete)
    assert cli.main(["--langs", "es", "fr"]) == 130

    # Spanish finished before the interruption: its file and cache entries survive.
    assert (tmp_path / "README.es.md").exists()
    assert not (tmp_path / "README.fr.md").exists()
    cache = json.loads((tmp_path / ".rosetta" / "cache.json").read_text())
    assert any(k.startswith("es:") for k in cache["entries"])

    # Resuming only asks the model for French.
    monkeypatch.setattr(FakeBackend, "complete", original)
    assert cli.main(["--langs", "es", "fr"]) == 0
    assert len(backends[-1].requests) == 1


def test_pause_between_requests(make_translator, monkeypatch):
    from readme_rosetta import translator as tr_module

    sleeps = []
    monkeypatch.setattr(tr_module.time, "sleep", sleeps.append)
    translator, _ = make_translator(pause=2.5)
    translator.translate_many(
        [f"Sentence {i} " + "word " * 600 for i in range(3)], "es"
    )
    assert sleeps == [2.5, 2.5]
