"""
README assembly: the language bar, translated file names and unified mode.
"""

import os
import re
from typing import Dict, Iterable, List, Optional

from .lang_codes import get_language, normalize_code
from .markdown_handler import split_front_matter
from .slug import heading_anchors

NAV_START = "<!-- rosetta:nav:start -->"
NAV_END = "<!-- rosetta:nav:end -->"
SECTION_MARK = "<!-- rosetta:translation:{code} -->"
GENERATED_NOTE = (
    "<!-- Generated by readme-rosetta from {source}. Edit {source} instead; "
    "changes to this file are overwritten. -->"
)

# Markers written by readme-rosetta <= 0.1.x
_LEGACY_TABLE = "<!-- <Original README.md> -->"
_LEGACY_SECTION = "<!-- <Rosetta Translations> -->"

_NAV_BLOCK = re.compile(
    re.escape(NAV_START) + r".*?" + re.escape(NAV_END) + r"[ \t]*\n?\n?", re.DOTALL
)
_NOTE_LINE = re.compile(
    r"^<!-- Generated by readme-rosetta .*?-->[ \t]*\n\n?", re.MULTILINE
)
_SECTION_RE = re.compile(r"\n*<!-- rosetta:translation:[\w-]+ -->")


def translation_path(readme: str, code: str) -> str:
    base, ext = os.path.splitext(readme)
    return f"{base}.{code}{ext}"


def discover_translations(readme: str) -> List[str]:
    """Language codes that have a translated file next to ``readme``."""
    directory = os.path.dirname(os.path.abspath(readme))
    name, ext = os.path.splitext(os.path.basename(readme))
    pattern = re.compile(rf"^{re.escape(name)}\.([A-Za-z_-]+){re.escape(ext)}$")
    codes = []
    for f in os.listdir(directory):
        m = pattern.match(f)
        if m:
            code = normalize_code(m.group(1))
            if code and code == m.group(1):
                codes.append(code)
    return sorted(codes)


def strip_rosetta(text: str) -> str:
    """Removes everything readme-rosetta ever added, returning the author's text."""
    text = _NAV_BLOCK.sub("", text)
    text = _NOTE_LINE.sub("", text)

    m = _SECTION_RE.search(text)
    if m:
        text = text[: m.start()].rstrip("\n") + "\n"
    if _LEGACY_SECTION in text:
        text = text[: text.index(_LEGACY_SECTION)].rstrip("\n") + "\n"

    if _LEGACY_TABLE in text:
        lines = text.split("\n")
        start = next(i for i, line in enumerate(lines) if _LEGACY_TABLE in line)
        end = start + 1
        while end < len(lines):
            line = lines[end].strip()
            if not line or line.startswith("|") or "Documentation Support" in line:
                end += 1
            else:
                break
        text = "\n".join(lines[:start] + lines[end:])
    return text


def _href(target: str, base_url: str) -> str:
    return f"{base_url.rstrip('/')}/{target}" if base_url else target


def build_nav(
    current: str,
    codes: Iterable[str],
    readme: str,
    source_lang: str,
    base_url: str = "",
    anchors: Optional[Dict[str, str]] = None,
) -> str:
    """
    One line of language links, e.g. ``🌐 **English** · [Español](README.es.md)``.
    With ``anchors`` (unified mode) links point at in-page headings instead.
    """
    readme_name = os.path.basename(readme)
    items = []
    for code in [source_lang] + sorted(c for c in set(codes) if c != source_lang):
        label = get_language(code).native
        if code == current:
            items.append(f"**{label}**")
        elif anchors is not None:
            items.append(f"[{label}](#{anchors.get(code, '')})")
        elif code == source_lang:
            items.append(f"[{label}]({_href(readme_name, base_url)})")
        else:
            items.append(
                f"[{label}]({_href(os.path.basename(translation_path(readme, code)), base_url)})"
            )
    return f"{NAV_START}\n🌐 " + " · ".join(items) + f"\n{NAV_END}\n\n"


def with_nav(text: str, nav: str, note: str = "") -> str:
    front, body = split_front_matter(text)
    return front + (note + "\n\n" if note else "") + nav + body.lstrip("\n")


def build_unified(
    source_body: str,
    sections: Dict[str, str],
    readme: str,
    source_lang: str,
) -> str:
    """Source text plus every translation appended below it, with in-page links."""
    parts = [source_body.rstrip("\n") + "\n"]
    marker_lines: Dict[str, int] = {}
    for code in sorted(sections):
        parts.append("\n" + SECTION_MARK.format(code=code) + "\n\n---\n\n")
        parts.append(sections[code].rstrip("\n") + "\n")
    body = "".join(parts)

    lines = body.split("\n")
    for i, line in enumerate(lines):
        m = re.match(r"^<!-- rosetta:translation:([\w-]+) -->$", line)
        if m:
            marker_lines[m.group(1)] = i

    anchors_list = heading_anchors(body)
    anchors = {}
    first = anchors_list[0][1] if anchors_list else ""
    anchors[source_lang] = first
    for code, line_no in marker_lines.items():
        anchors[code] = next((a for ln, a in anchors_list if ln > line_no), "")

    nav = build_nav(source_lang, list(sections), readme, source_lang, anchors=anchors)
    return with_nav(body, nav)
